// English copy of labels.js — same keys, laid over the Indonesian at startup when the
// device language is English (see utils/lang.js). A key missing here shows in Indonesian.
export const labels = {
	appName: "Depot OAK",
	home: "Home",
	loggedInAs: "Logged in as",
	logout: "Log out",
	// Bottom nav + greeting
	navHome: "Home",
	navGate: "Gate",
	navEir: "EIR",
	navMonitor: "Monitor",
	navProfile: "Profile",
	navHistory: "History",
	navSchedule: "Schedule",
	navSurveyList: "Survey",
	navPosFix: "Lowering",
	navLeak: "Leak Check",
	navTankPos: "Position",
	// --- Profile ---
	profileTitle: "Profile",
	profileBranchTitle: "Branch Scope",
	profileBranchAll: "All branches — unrestricted",
	profilePhotoChange: "Change profile photo",
	profilePhotoRemove: "Remove photo",
	profilePhotoSaved: "Profile photo updated",
	profilePhotoRemoved: "Profile photo removed",
	profilePhotoFailed: "Photo could not be saved. Use JPG/PNG/WEBP, max 8 MB.",
	profileAccessTitle: "Menus you can open",
	profileAccessEmpty: "No menus available yet",
	profileAccessHint: "Set by your account's permissions. Contact an admin if something is missing.",
	// --- Change password ---
	pwTitle: "Change Password",
	pwHint: "Change your account password",
	pwOld: "Current Password",
	pwNew: "New Password",
	pwConfirm: "Repeat New Password",
	pwShow: "Show password",
	pwHide: "Hide password",
	pwRequirements: "Password does not meet the requirements yet",
	pwSubmit: "Save Password",
	pwSaving: "Saving…",
	pwIncomplete: "Fill in all fields.",
	pwMismatch: "The new password and its repeat do not match.",
	pwSame: "The new password must be different from the current one.",
	pwSuccess: "Password changed.",
	pwFailed: "Password could not be changed.",
	pwWrongOld: "Current password is wrong.",
	// --- Phone notifications (Web Push) ---
	pushTitle: "Phone Notifications",
	pushHint: "Rings on your phone even when the app is closed",
	pushActive: "Active on this device",
	pushInactive: "Not active on this device yet",
	pushEnable: "Enable",
	pushDisable: "Turn off",
	pushWorking: "Processing…",
	pushEnabled: "Phone notifications enabled.",
	pushDisabled: "Phone notifications turned off on this device.",
	pushUnsupported: "This browser does not support notifications.",
	pushDenied: "Notifications are blocked. Allow them first in your browser/phone site settings.",
	pushServerOff: "Phone notifications are not set up on the server yet. Contact an admin.",
	pushFailed: "Could not enable notifications.",
	pushTest: "Test",
	notifTypesHint: "Notification types this phone receives. Turned-off ones don't ring and don't show in the bell — on this phone only.",
	pushTestSent: "Test notification sent. Check your phone screen.",
	pushTestNoDevice: "No registered device. Turn notifications off and on again.",
	pushTestFailed: "Could not send the test notification.",
	pushSwTimeout: "The app is not ready to receive notifications yet. Close and reopen the app; if this keeps appearing, contact an admin.",
	pushIosHint: "On iPhone, notifications only work after the app is added to the Home Screen.",
	// --- Mandatory notifications (NotifGate) ---
	pushGateTitle: "Enable notifications first",
	pushGateBody:
		"New work is sent through phone notifications. Until notifications are active on this device, you cannot use the app.",
	pushGateBtn: "Enable Notifications",
	pushGateAllow: 'Tap "Allow" on the permission prompt that appears.',
	pushGateDeniedTitle: "Notifications are blocked on this device",
	pushGateDeniedBody:
		"Notification permission was denied before, so the app cannot ask again. Allow it in settings, then tap Check Again.",
	pushGateAndroidStep1: "Open phone Settings > Apps > Depot OAK > Notifications.",
	pushGateAndroidStep2: "Turn notifications on, then come back to this app.",
	pushGateIosStep1: "Open iPhone Settings > Depot OAK > Notifications.",
	pushGateIosStep2: 'Turn on "Allow Notifications", then come back to this app.',
	pushGateRecheck: "Check Again",
	pushGateSkip: "Skip for now",
	pushGateSkipHint:
		"Without notifications, new work does not reach your phone. This screen appears again in 30 minutes.",
	pushGateWhy: "Why is this required?",
	pushGateWhyBody:
		"Gate, EIR, cleaning and M&R work is handed out through notifications. Without them, you only see your work if you happen to open the app.",
	// --- Mandatory install (InstallGate) ---
	installTitle: "Install Depot OAK first",
	installBody:
		"On a phone, Depot OAK only works from the home screen — not from the browser. Follow the steps below, then open the app from the home screen.",
	installBtn: "Install Now",
	installIosTitle: "How to install on iPhone",
	installIosStep1: "Tap the Share button at the bottom of Safari.",
	installIosStep2: 'Choose "Add to Home Screen".',
	installIosStep3: 'Tap "Add", then open Depot OAK from the home screen.',
	installIosSafari:
		"Open this page in Safari first — Chrome on iPhone cannot install apps.",
	installAndroidTitle: "How to install on Android",
	installAndroidStep1: "Tap the ⋮ menu at the top right of the browser.",
	installAndroidStep2: 'Choose "Install app" or "Add to Home screen".',
	installDoneTitle: "Depot OAK is installed",
	installDoneBody:
		"Close this page, then open Depot OAK from your phone's home screen. You log in inside the app.",
	installWebviewTitle: "Open in a browser first",
	installWebviewBody:
		"This page is open inside another app, which cannot install Depot OAK. Tap the ⋮ menu then \"Open in Chrome\", or copy the link below and paste it in Chrome.",
	installWebviewIosBody:
		"This page is open inside another app, which cannot install Depot OAK. Copy the link below, then paste it in Safari.",
	installCopyLink: "Copy link",
	installCopied: "Link copied",
	installRepeatTitle: "You opened it in the browser again",
	installRepeatBody:
		"This is time #{n}. Until Depot OAK is installed on the home screen, work notifications will not reach your phone — including while it is locked.",
	installRepeatHelp: "Trouble installing? Ask Admin Ops for help.",
	installWhy: "Why install it?",
	installWhyBody:
		"Work notifications can only reach an installed app. If it is opened in the browser, notifications won't arrive while the phone is locked.",
	greeting: "Hi",
	menuEmptyTitle: "No menus for this account yet",
	menuEmptyBody: "Your account has no field role yet. Contact Admin Ops to get access.",
	openDesk: "Open Desk",
	openDeskHint: "Manage bookings, rates and reports in ERPNext.",
	// --- Connection status ---
	offlineBanner: "Offline mode — data from the last connection. Saves cannot reach the system yet; connect to the internet first.",
	// --- Gate: 3-step flow ---
	gateStepContainer: "Container",
	gateStepVehicle: "Truck and driver",
	gateStepDone: "Confirm",
	gateStepOf: "Step {n} of 3",
	gateNext: "Next: truck and driver",
	gateRescan: "Scan again",
	gateSelectedCount: "{n} / {max} selected",
	gateNoNumber: "— no number",
	gateNoNumberHint: "Fill in the container number on the booking",
	gateNoNumberChip: "Missing data",
	gateAutofill: "Cargo and EMKL filled in automatically from the booking",
	gateFromBooking: "from booking",
	gateExtra: "Additional details",
	gateDoneTitle: "Voucher created",
	gateDoneHint: "Hand the voucher to the driver. The next truck can be scanned right away.",
	gateDoneNext: "Scan next truck",
	gateNeedsOnline: "Gate needs internet",
	gateNeedsOnlineHint:
		"The booking's payment and block status must be checked live with the server before a voucher is made, so this screen cannot be used offline. Connect to the internet first.",
	// --- Home ---
	homeRoles: "{n} roles",
	homeSearchPlaceholder: "Search container no., booking, or voucher",
	homeScanAria: "Scan booking code",
	homeSearchAria: "Search",
	homeToday: "Today",
	homeTilesEdit: "Edit",
	homeTilesTitle: "Arrange cards",
	homeTilesHint: "Pick the cards you look at most — all of them is fine, the home screen just gets longer. The numbers are real, so you can compare before choosing.",
	homeTilesSaved: "Home cards updated",
	homeTilesResetDone: "Home cards reset to default",
	homeTodayMonitor: "View monitor",
	homeTileEirOpen: "EIR not done",
	homeTileEirOpenSub: "{n} outbound EIRs waiting",
	homeTileMr: "Active M&R",
	homeTileMrSub: "{n} awaiting approval",
	homeTilePeriodic: "Active Periodic Test",
	homeTileMonitor: "Tanks in depot",
	homeTileMonitorSub: "all active tanks",
	homeTileSchedule: "Today's schedule",
	homeTileScheduleSub: "{n} not done",
	homeTileSurvey: "Surveys today",
	homeTileLowering: "Lowering queue",
	homeTileLoweringSub: "{n} tanks waiting",
	homeTileUnlocated: "Tanks without position",
	homeTileUnlocatedSub: "{n} not recorded",
	homeTileGateIn: "Tanks in",
	homeTileGateInSub: "{n} without EIR",
	homeTileGateOut: "Tanks out",
	homeTileGateOutSub: "{n} bookings pending",
	homeTileEirReview: "EIR review",
	homeTileEirReviewSub: "oldest {age}",
	homeTileCleaning: "Active cleaning",
	homeTileCleaningSub: "{n} not started",
	homeTileClear: "No tasks",
	// Waiting on you
	homeWaiting: "Waiting on you",
	homeWaitingCount: "{n} items",
	homeWaitingEmpty: "Nothing waiting. Your queue is clear.",
	homeWaitingTitle: "Arrange queue",
	homeWaitingHint: "Tick the queues you want to see, order them with the arrows. Saved on this phone for your account.",
	homeWaitingUp: "Move up",
	homeWaitingDown: "Move down",
	homeWaitingSaved: "Home queue updated",
	homeWaitingResetDone: "Home queue reset to default",
	waitEirReviewOne: "EIR {ref} awaiting review",
	waitEirReviewMany: "{n} EIRs awaiting review",
	waitEirOpenOne: "EIR {ref} not done yet",
	waitEirOpenMany: "{n} EIRs not done yet",
	waitEirOutMany: "{n} EIR-Outs waiting",
	waitCleaningIdleOne: "Cleaning {ref} not started",
	waitCleaningIdleMany: "{n} cleaning orders not started",
	waitMrApprovalOne: "M&R {ref} awaiting approval",
	waitMrApprovalMany: "{n} M&Rs awaiting approval",
	waitPeriodicApprovalOne: "Periodic Test {ref} awaiting approval",
	waitPeriodicApprovalMany: "{n} Periodic Tests awaiting approval",
	waitLoweringMany: "{n} tanks waiting to be lowered",
	waitSurveyReadyMany: "{n} tanks ready for survey",
	waitPositionOrderMany: "{n} survey tanks without a position",
	waitCleaningReviewOne: "Cleaning {ref} awaiting review",
	waitCleaningReviewMany: "{n} cleaning orders awaiting review",
	waitMrReviewOne: "M&R {ref} awaiting review",
	waitMrReviewMany: "{n} M&Rs awaiting review",
	waitPeriodicReviewOne: "Periodic Test {ref} awaiting review",
	waitPeriodicReviewMany: "{n} Periodic Tests awaiting review",
	waitScheduleOverdueMany: "{n} overdue schedules not done",
	ageNow: "just now",
	ageMinutes: "{n} min",
	ageHours: "{n} h",
	ageDays: "{n} d",
	homeGroupOps: "Operations",
	homeGroupYard: "Yard",
	homeGroupHistory: "History",
	// --- "More" sheet ---
	navMore: "More",
	navTabsEdit: "Edit tabs",
	navTabsTitle: "Bottom tab bar",
	navTabsHint: "Pick up to 3 modules for the bottom bar. Home and More are always there; the rest can still be opened from here.",
	navTabsSave: "Save",
	navTabsCancel: "Cancel",
	navTabsReset: "Default",
	navTabsSaved: "Bottom tab bar updated",
	navTabsResetDone: "Bottom tab bar reset to default",
	moreModules: "Other modules",
	moreAccount: "Account and system",
	moreRoles: "Active roles",
	moreRolesRest: "+{n} more",
	moreTheme: "Appearance",
	themeSystem: "Automatic",
	themeLight: "Light",
	themeDark: "Dark",
	themeSystemHint: "Follows phone settings",
	moreSettings: "Settings",
	moreSettingsHint: "Notifications, photo, and password",
	moreDeskHint: "Full ERPNext view",
	moreClose: "Close",
	// Notification bell
	notifications: "Notifications",
	notifEmpty: "No notifications yet",
	notifMarkAll: "Mark all as read",
	notifSound: "Notification sound",
	notifSoundOn: "Notification sound on",
	notifNoAccess: "You don't have access to this data.",
	search: "Search tank number…",
	filter: "Filter",
	principal: "Principal",
	status: "Status",
	yardZone: "Yard Zone",
	depot: "Depot",
	all: "All",
	loading: "Loading…",
	error: "Something went wrong",
	retry: "Retry",
	empty: "No data",
	detail: "Tank Detail",
	type: "Type",
	capacity: "Capacity",
	tare: "Tare (kg)",
	maxGross: "Max Gross Weight (kg)",
	lastCargo: "Last Cargo",
	lastTest: "Last Periodic Test Date",
	eirInDate: "Last EIR-In Date",
	eirOutDate: "Last EIR-Out Date",
	location: "Yard Location",
	documents: "Documents",
	noDocuments: "No documents yet",
	viewPrint: "View / Print",
	repairs: "Repairs",
	noRepairs: "No repairs",
	estimateTotal: "Estimate Total",
	billing: "Billing",
	technician: "Technician",
	gate: "Gate",
	gateDesc: "Scan / validate booking & issue voucher",
	bookingCode: "Booking Code",
	bookingCodePlaceholder: "OAK-XXXXXX",
	validate: "Validate",
	direction: "Direction",
	// Gate — scan/type code
	gateScanTitle: "Scan / Type Code",
	gateScanPlaceholder: "Code / Container No. (OAK-… / ORD-… / ABCD1234567)",
	gateChoicesTitle: "Several active bookings — pick one",
	gateScan: "Camera Scan",
	gateScanClose: "Close",
	gateScanError: "Cannot access the camera — type the code manually.",
	gateScanHint: "Point the camera at the booking / voucher QR.",
	gateLookup: "Search",
	branch: "Branch",
	bookingStatus: "Booking Status",
	customer: "Customer",
	liftService: "Lift Service",
	paymentType: "Payment Type",
	paymentStatus: "Payment Status",
	doReference: "DO Reference",
	gateContainers: "Container List",
	gatePayBlocked: "Payment must be made in cash at the cashier first.",
	gateNotSubmitted: "Booking is paid but not confirmed/submitted yet — contact an admin.",
	gateBlockedTitle: "Cannot be processed at the gate yet",
	gateInvoiceNo: "Invoice No.",
	gateGenerate: "Generate Voucher",
	gateSelectMax2: "Select at most 2 containers per voucher.",
	gateGenerated: "Voucher created",
	gateNoContainers: "No containers.",
	gateBon: "Voucher",
	gateSectionBooking: "Booking Data",
	gateSectionPayment: "Payment",
	gateSectionNote: "Notes",
	gateReadyOut: "Ready to leave",
	gateHeldBy: "Not finished",
	gateHeldHint: "This container cannot leave until the orders below are finished.",
	gateOutReadyCount: "containers ready to leave",
	gateOutNoneReady: "No containers ready to leave yet",
	gateOutNoneReadyHint:
		"All containers in this booking are still waiting for the following orders to finish. A voucher can be made once those orders are done.",
	gateOutUnready: "Not ready",
	gateAlreadyOut: "Already out",
	// Gate — EMKL / Shipper pickers
	gateShipperEmkl: "EMKL / Transporter",
	gateShipperOther: "Customer",
	gateShipperEmpty: "Customer not found",
	// Gate — vehicle / driver form
	optional: "optional",
	gateRequiredMissing: "Fill in the required fields",
	vCondition: "Condition",
	vRo: "R/O",
	vEmkl: "EMKL / Hauler",
	vShipper: "Shipper (Factory)",
	vDestination: "Destination",
	vDateBongkar: "Unloading Date",
	vDateMuat: "Loading Date",
	cancelBtn: "Cancel",
	backBtn: "Back",
	truckPlate: "Truck Plate",
	driverName: "Driver Name",
	registerGate: "Record Gate-In",
	gateOk: "Gate-in recorded",
	codeInvalid: "Invalid / inactive code",
	reset: "Start over",
	// EIR checklist
	eir: "EIR",
	eirTitle: "EIR Checklist",
	eirCombinedSubtitle: "In & out inspections in one list",
	eirStartTitle: "Start Inspection",
	eirStartHint: "Press start to open the checklist. Work time is counted from here.",
	eirStartBtn: "Start",
	eirStartedAt: "Started",
	eirWorkedBy: "Worked on by {name}",
	orderEditedBy: "Last edited by {name}",
	sectionDoing: "In progress",
	sectionTodo: "To do",
	eirBadgeIn: "In",
	eirBadgeOut: "Out",
	eirBadge: "EIR",
	eirNavPrev: "Previous",
	eirNavNext: "Next",
	eirSelect: "Select",
	eirSelectCancel: "Cancel",
	eirBatchOpen: "Open",
	eirBatchExit: "Exit batch",
	// Batch EIR
	eirBatchOf: "of",
	eirBatchTitle: "Batch",
	eirBatchOpenBtn: "Open batch",
	eirBatchOpenHint: "Move between EIRs without going back to the list.",
	eirBatchResume: "Resume",
	eirBatchOpenOne: "Open",
	eirBatchSelectAll: "Select all",
	eirBatchNotStarted: "Not started",
	eirBatchTodoWord: "To do",
	eirBatchSentWord: "Sent",
	eirBatchSentAt: "Sent",
	eirBatchOpenNow: "Open now",
	eirStepWord: "step",
	eirBatchVoucherTitle: "{n} EIRs from the same voucher",
	eirBatchVoucherHint: "voucher data is filled in once for all.",
	eirVoucherForCount: "applies to {n} EIRs",
	eirVoucherFromBatch: "already filled from the batch",
	// EIR form steps
	eirRequired: "required",
	eirNoFittings: "No fittings boxes for this tank.",
	eirStepTank: "Tank data",
	eirStepFittings: "Fittings",
	eirStepDamage: "Damage",
	eirStepPhotos: "Photos",
	eirStepReview: "Review & send",
	eirStepNext: "Next",
	eirStepBack: "Back",
	eirSaveDraftExit: "Save draft",
	eirAutosaveShort: "Autosaved",
	eirSavingShort: "Saving…",
	eirSavedShort: "Saved",
	eirStartOne: "Start inspection",
	eirStartBatchHint: "Start time is counted separately per EIR.",
	// Last step: summary + send
	eirReviewSummary: "Summary",
	eirReviewFilled: "filled",
	eirReviewBlank: "blank",
	eirReviewDamage: "damage",
	eirReviewPhotos: "photos",
	eirBatchStatusTitle: "Batch status",
	eirBatchReadyToSend: "Ready to send",
	eirBatchNotSentYet: "Not sent yet",
	eirSendOne: "Send",
	eirSendClose: "& close batch",
	eirSendHintLast: "then back to the list",
	eirSendHintNext: "then on to",
	eirSendHintSent: "already sent",
	eirMinutes: "min",
	// Batch closing screen
	eirBatchDoneTitle: "Batch finished",
	eirBatchDoneSent: "EIRs sent",
	eirBatchDoneNote: "A cleaning order is created automatically for tanks whose status stays Empty dirty.",
	eirBatchDoneBack: "Back to list",
	eirBatchDoneNew: "Open new batch",
	eirSource: "Data Source",
	eirFetch: "Fetch Data",
	containerNumber: "Container Number",
	containerNumberPlaceholder: "e.g. EIRU1234567",
	eirType: "EIR Type",
	eirHeader: "Tank Data",
	prefix: "Prefix",
	number: "Number",
	checkDigit: "Cd",
	vessel: "Vessel",
	serialNo: "Serial No",
	dateManufacture: "Date of Manufacture",
	tankSize: "Size",
	equipmentType: "Equipment Type",
	eirTankHint:
		"Belongs to the tank master, fill it in once — later EIRs reuse it. Ticked items are already in the master; fill in blanks if readable on the plate, correct them if different.",
	eirTankFromMaster: "from master",
	eirOptional: "optional",
	eirTankAuto: "Filled by system",
	ownerPrincipal: "Principal (Owner)",
	exVessel: "Ex Vessel",
	tanggal: "Date",
	tankStatus: "Tank Status",
	emptyClean: "Empty Clean",
	emptyDirty: "Empty Dirty",
	laden: "Laden",
	cargo: "Cargo",
	cargoSearch: "Search cargo…",
	selectPlaceholder: "Select…",
	selectSearch: "Search…",
	cargoHint: "Changes the container's Last Cargo — saved when the EIR is submitted.",
	checklist: "Damage Checklist",
	colItem: "Item",
	colDamage: "Damage Code",
	colRepair: "Repair Code",
	colRemarks: "Remarks",
	colRemarksManual: "Remarks (manual, optional)",
	photo: "Photo",
	photoCamera: "Camera",
	photoGallery: "Gallery",
	addPhoto: "Add Photo",
	photoError: "Photo upload failed",
	photoCaption: "Photo note…",
	// In-app viewfinder
	camTitle: "Take Photo",
	camShutter: "Take photo",
	camDone: "Done",
	camClose: "Close camera",
	camTorch: "Torch",
	camZoom: "Zoom",
	camStarting: "Starting camera…",
	camCount: "photos taken",
	camShotUploading: "sending",
	camShotSent: "sent",
	camShotParked: "on phone",
	camShotFailed: "failed",
	camRetakeHint: "Some photos failed — retake the ones marked red.",
	photoMarkUploading: "Uploading…",
	photoMarkSent: "Sent to server",
	photoMarkParked: "Saved on phone — sent on Send",
	photoMarkFailed: "Failed",
	photoMarkFailedHint: "Photo could not be saved — please retake it.",
	acceptableHint: "Leave rows in good condition (Acceptable) blank.",
	// Search-to-add checklist
	checklistSearchDamaged: "Search a damaged section / part…",
	checklistEmpty: "No damage yet. Search a section / part above to add one.",
	checklistAllAdded: "All parts have been added.",
	// Mandatory before submit (EIR-In)
	eirNeedComplete: "Complete before submitting:",
	eirNeedCargo: "Cargo (Last Cargo)",
	eirNeedTankStatus: "Tank Status",
	eirNeedSignature: "Signature",
	// Quick photos + section search
	bulkPhotoTitle: "Quick Photos",
	bulkPhotoHint: "Shoot first without picking a section — an admin sorts them into sections later.",
	sectionSearch: "Search section / item…",
	sectionSearchEmpty: "Nothing matched.",
	// EIR photo sorting (admin)
	eirSortTitle: "Sort Photos",
	eirSortDesc: "Assign a section to quick photos",
	eirSortEmpty: "No EIR with unsorted photos.",
	eirSortPhotosEmpty: "All photos sorted. 🎉",
	eirSortPick: "Pick a section for this photo",
	eirSortAssigned: "Photo assigned to a section",
	eirSortUnsortedCount: "photos unsorted",
	eirSortOpen: "Sort",
	signOff: "Signature & Notes",
	truckNo: "Truck No.",
	emkl: "EMKL",
	driverPhone: "Driver Phone",
	shipper: "Shipper",
	referredVoucher: "Referred Voucher",
	voucherHintIn: "EIR-In: data taken from the Order Bongkar.",
	voucherHintOut: "EIR-Out: data taken from the Order Muat.",
	eirRemarks: "Remarks",
	reffDoc: "Reff Doc",
	reffDocHint: "Reference document no. (optional).",
	reffDocAutoHint: "Filled from the booking, can be changed.",
	officer: "Officer",
	saveDraft: "Save Draft",
	submitEir: "Submit EIR",
	eirCreated: "EIR created",
	eirDraftHint: "The EIR draft is created/opened automatically when fetching data.",
	eirAutosaveHint: "Changes are saved automatically.",
	autosaveHint: "Changes are saved automatically.",
	// Confirm-before-submit dialog
	confirmSubmitTitle: "Submit order?",
	confirmSubmitMessage: "Are you sure you want to submit this order? This cannot be undone.",
	confirmSubmitYes: "Yes, Submit",
	confirmCancel: "Cancel",
	// EIR Out
	eirOutTitle: "EIR Out",
	eirOutSubtitle: "Outbound survey — compare with last EIR-In",
	eirOutDesc: "Inspect the tank before it is loaded out",
	eirOutSearch: "Search container no. / Order Muat…",
	eirOutEmpty: "No EIR-Out waiting",
	eirOutNoOrder: "No Order Muat",
	eirOutCompare: "Compare Last EIR-In",
	eirOutPrevDamage: "Findings at EIR-In",
	eirOutPrevFittings: "Fittings at EIR-In",
	eirOutPrevClean: "EIR-In: no findings",
	eirOutPrevPhotos: "EIR-In Photos",
	eirOutNoBaseline: "No previous EIR-In to compare with",
	eirOutWillReady: "Once approved by Adm Ops, the tank is recorded as OUT OF DEPOT",
	// Tank fittings
	fittingsTitle: "Tank Fittings",
	fittingsHint: "Fill in as per the boxes on the EIR form. Leave blank if not checked — blank ≠ zero.",
	fittingsHintOut: "EIR-In figures are prefilled as a starting point. Check physically, correct if different — the difference is the basis for a claim.",
	fittingValue: "Quantity",
	fittingOther: "Other…",
	fittingOtherPlaceholder: "Type your own",
	fittingBackToList: "↺ Pick from list",
	fittingBaseline: "EIR-In:",
	// Seal numbers at load-out
	eirOutSealsTitle: "Seal No.",
	eirOutSealsHint: "Record every seal fitted. Add as many rows as there are seals.",
	eirOutSealNoPlaceholder: "Seal number",
	eirOutSealRemarkPlaceholder: "Remarks (seal position, etc.) — optional",
	eirOutSealAdd: "Add Seal",
	eirOutConfirmReadyTitle: "Send EIR-Out for review?",
	eirOutBackToList: "Back to list",
	savingDraft: "Saving…",
	draftSaved: "Saved",
	photoUploading: "Uploading photo…",
	photoParked: "Photo saved on phone — it will be sent on Send.",
	sendUploadingPhoto: "Uploading photo",
	sendSaving: "Saving to server…",
	eirSubmitted: "EIR submitted",
	eirSendReview: "Send for Review",
	eirSentForReview: "EIR sent for Adm Ops review",
	newEir: "EIR for another container",
	// EIR history
	eirHistory: "History",
	eirHistoryTitle: "EIR History",
	eirHistoryDesc: "EIRs you created",
	eirHistorySearch: "Search container no. / EIR…",

	// --- History menus — shared ---
	depotLabel: "Depot",

	// Gate history
	gateHistoryTitle: "Gate History",
	gateHistoryDesc: "Gate-in/out vouchers already made",
	gateHistorySearch: "Search container / truck / booking…",
	gateHistoryToday: "today",
	gateHistoryAll: "All history",
	gateHistoryCount: "gate entries",
	gateTruck: "Truck No.",
	gateDriver: "Driver",
	gateBooking: "Booking",
	gateInTime: "Gate In",
	gateOutTime: "Gate Out",
	gateOrder: "Order",
	gateEir: "EIR",
	gateStatus: {
		Active: "In Depot",
		Gate_In_Completed: "Gated In",
		EIR_Completed: "EIR Completed",
		Gate_Out_Completed: "Left",
		Cancelled: "Cancelled",
	},

	// Cleaning history
	cleaningHistoryTitle: "Cleaning History",
	cleaningHistoryDesc: "Completed / cancelled cleaning orders",
	cleaningHistoryCount: "cleaning orders",
	cleaningStatusCompleted: "Completed",
	cleaningStatusCancelled: "Cancelled",
	cleaningDateIssue: "Date of Issue",
	cleaningPlaceIssue: "Place of Issue",
	cleaningSignedBy: "Signed By",
	cleaningWorkedBy: "Worked By",
	cleaningStartAt: "Wash Start",
	cleaningEndAt: "Wash End",
	cleaningRemarks: "Notes",

	// M&R history
	mrHistoryTitle: "M&R History",
	mrHistoryDesc: "Completed / rejected / cancelled repair orders",
	mrHistorySearch: "Search container no. / repair…",
	mrHistoryCount: "repair orders",
	mrDamages: "Damage",
	mrUsedItems: "Items Used",
	mrTechnician: "Technician",

	// Storage history
	storageHistoryTitle: "Storage History",
	storageHistoryDesc: "Container movements & placement in the yard",
	storageHistorySearch: "Search container no.…",
	storageHistoryCount: "movements",
	storageZoneMove: "Zone Move",
	storageStatusMove: "Status Change",
	storageMovedBy: "By",
	storageEvent: { Yard: "Yard", Status: "Status", Combined: "Yard + Status" },

	// Monitor history
	monitorHistoryTitle: "Monitor History",
	monitorHistoryDesc: "Container activity timeline",
	monitorHistorySearch: "Search container no. / activity…",
	monitorHistoryCount: "activities",
	monitorRefDoc: "Document",
	activityVoided: "Cancelled",
	activityVoidedNote: "The source document was cancelled — this action did not happen.",
	monitorPerformedBy: "By",

	// EIR history detail
	eirHistoryCount: "EIRs",
	eirTankStatus: "Tank Status",
	eirDate: "Date",
	eirVoucher: "Voucher",
	eirTruck: "Truck No.",
	eirDriver: "Driver",
	eirEmkl: "EMKL",
	eirDamages: "Damage",
	eirNoDamage: "No damage recorded.",
	eirChecklistDamage: "Damage Checklist",
	eirPhotosTitle: "Inspection Photos",
	eirNoPhotos: "No photos yet.",
	eirPhotoUnsorted: "Unsorted",
	eirDamageCode: "D",
	eirRepairCode: "R",
	// Request revision on a completed EIR
	eirReqRevision: "Request Revision from Admin Ops",
	eirReqRevisionHint: "Ask Admin Ops to reopen this EIR so it can be corrected.",
	eirReqRevisionReason: "Revision reason (optional)",
	eirReqRevisionSend: "Send Request",
	eirReqRevisionSent: "Revision request sent to Admin Ops",
	// Withdraw a Pending-Review EIR
	eirWithdrawReview: "Withdraw & Fix",
	eirWithdrawReviewHint: "Withdraw this EIR from the review queue to fix it, then send it again.",
	eirWithdrawReviewDone: "EIR withdrawn — fix it and send it again",

	prev: "Previous",
	next: "Next",
	eirStatusDraft: "Draft",
	eirStatusSubmitted: "Completed",
	eirStatusCancelled: "Cancelled",
	eirStatusPendingReview: "Pending Review",
	eirStatusRevision: "Revision Requested",
	eirDraftList: "Draft EIRs",
	eirCompleteList: "Completed EIRs",
	eirReviewList: "Sent for Review",
	eirReviewEmpty: "No EIRs awaiting review.",
	eirReviewCount: "awaiting review",
	eirListMore: "See all",
	eirDraftEmpty: "No EIR drafts yet.",
	eirCompleteEmpty: "No completed EIRs yet.",
	eirResume: "Resume",
	// Pending EIR worklist
	eirPendingEmptyHint: "Created automatically from Order Bongkar / Order Muat",
	eirPendingSearch: "Search container no. / voucher…",
	eirFilterAll: "All",
	eirFilterEmptyStarted: "No EIRs in progress yet.",
	eirFilterEmptyNotStarted: "All EIRs have been started. 🎉",
	eirFilterEmptyIn: "No inbound EIRs in this list.",
	eirFilterEmptyOut: "No outbound EIRs in this list.",
	eirOpenBtn: "Open",
	eirBackToList: "EIR List",
	eirVoucherLocked: "Set automatically from the Order Bongkar when the voucher is made.",
	// Follow-up orders
	eirFollowupTitle: "Follow-up (Automatic Orders)",
	eirCreateCleaning: "Create Cleaning Order",
	eirCreateCleaningHint: "Tank Empty Dirty — create a Cleaning Order on submit.",
	eirCreateRepair: "Create M&R (Repair Order)",
	eirCreateRepairHint: "Damage found — create an M&R draft on submit.",
	// Signature
	signature: "EIR Creator Signature",
	signedBy: "Signed by",
	signHint: "Sign in the box above.",
	signAgain: "Sign again",
	clear: "Clear",
	signatureError: "Signature upload failed",
	// Cleaning Order
	cleaningTitle: "Cleaning Order",
	cleaningOrdersHint: "Pick a cleaning order to work on",
	cleaningCargoHistory: "Cargo History",
	cleaningNoCargoHistory: "No cargo history yet.",
	cleaningStartFull: "Start Cleaning",
	cleaningStartFirst: "Start cleaning first before it can be finished.",
	cleaningStartGate: "This order has not started. Start it first to fill in the cleaning details.",
	cleaningNotStarted: "Not Forwarded",
	cleaningRequested: "Requested services",
	cleaningStartAuto: "Start time is recorded automatically",
	cleaningStepMethod: "Method",
	cleaningStepSign: "Signature",
	cleaningDurationMin: "{n} min",
	cleaningWorkWindow: "Start {start} – {end}",
	cleaningSave: "Save",
	cleaningComplete: "Send for Review",
	cleaningCompleteHint: "Admin Ops checks it before the order is truly finished.",
	cleaningSaved: "Saved",
	navCleaning: "Cleaning",
	cleaningOrdersSearch: "Search container no. / order…",
	cleaningOrdersEmpty: "No open cleaning orders.",
	cleaningOrdersList: "Cleaning Order List",
	cleaningOrdersCount: "waiting",
	cleaningFilterTodo: "To do",
	cleaningFilterEmptyTodo: "All cleaning has been started. 🎉",
	cleaningFilterEmptyStarted: "No cleaning in progress yet.",
	cleaningReviewList: "Sent for Review",
	cleaningReviewEmpty: "No cleaning awaiting review.",
	cleaningStatusPendingReview: "Pending Review",
	cleaningStatusRevision: "Revision Requested",
	cleaningCompleteList: "Completed Cleaning",
	cleaningCompleteEmpty: "No completed cleaning yet.",
	cleaningListMore: "See all",
	cleaningWithdrawReview: "Withdraw & Fix",
	cleaningWithdrawReviewDone: "Order withdrawn — fix it and send it again",
	cleaningReqRevision: "Request Revision from Admin Ops",
	cleaningReqRevisionHint: "Ask Admin Ops to reopen this order so it can be corrected.",
	cleaningReqRevisionReason: "Revision reason (optional)",
	cleaningReqRevisionSend: "Send Request",
	cleaningReqRevisionSent: "Revision request sent to Admin Ops",
	createdOn: "Created",
	cleaningOrder: "Cleaning Order",
	cleaningType: "Cleaning Method",
	cleaningNoMethod: "Cleaning method not set by Admin Ops yet.",
	cleaningInstructions: "Cleaning Instructions",
	cleaningTypeUnset: "Not set",
	cleaningSelectServices: "Select cleaning services (more than one allowed)",
	cleaningServicesCount: "services",
	cleaningSearchServices: "Search services…",
	cleaningNoMatch: "No matching services.",
	cleaningNoPricedItems: "The owner has no cleaning services in the price list.",
	cleaningPending: "Pending",
	cleaningInProgress: "In Progress",
	cleaningStart: "Start",
	cleaningStarted: "Cleaning started",
	cleaningBack: "Back",
	cleaningTankDetails: "Tank Data",
	cleaningRefEir: "EIR Reference",
	cleaningChecklist: "Cleanliness Checklist",
	cleaningYes: "Yes",
	cleaningNo: "No",
	cleaningNote: "Note (if no)…",
	cleaningGasFree: "Gas Free",
	cleaningO2: "O₂ %",
	cleaningLel: "LEL %",
	cleaningSeals: "Seal Numbers",
	cleaningSealManhole: "Manhole Seal",
	cleaningSealAirline: "Airline Seal",
	cleaningSealBottom: "Bottom Outlet Seal",
	// QC photos
	cleaningQcPhotos: "QC Photos",
	cleaningQcPhotoAdd: "Add Photo",
	cleaningQcPhotoEmpty: "No QC photos yet",
	cleaningSignature: "Surveyor Signature",
	cleaningResign: "Sign again",
	cleaningUploading: "Uploading…",
	cleaningSubmitted: "Cleaning sent for Admin Ops review",
	cleaningTankType: "Tank Type",
	cleaningClient: "Client / Principal",
	cleaningCapacity: "Capacity (L)",
	cleaningTare: "Tare (kg)",
	cleaningMgw: "MGW (kg)",
	cleaningPrevCargo: "Previous Cargo",
	cleaningMfgDate: "Mfg. Date",
	cleaningLastTest: "Last Periodic Test",
	lastTestHint: "This tank's last periodic test — including ones done by a vendor / other depot, which have no M&R here.",
	lastTestSaved: "Last periodic test date saved",
	// M&R
	mrTitle: "M&R",
	mrTitleFull: "M&R (Maintenance & Repair)",
	navMr: "M&R",
	// Periodic Test
	navPeriodic: "Periodic Test",
	ptTitleFull: "Periodic Test",
	ptExecOrdersHint: "Periodic tests ready to work on",
	ptWorkTitle: "Periodic Test",
	ptHistoryTitle: "Periodic Test History",
	mrOrdersHint: "Pick an M&R to work on",
	mrOrdersSearch: "Search container no. / M&R…",
	mrOrdersEmpty: "No open M&R.",
	mrBack: "Back",
	mrTankDetails: "Tank Data",
	mrWarehouse: "Warehouse",
	mrDamagesTitle: "Damage Findings (EIR)",
	mrCodeDamage: "Damage",
	mrCodeRepair: "Repair",
	mrUsedTitle: "Services & Parts Used",
	mrUsedHint: "Pick services/parts from the catalogue. Part stock is deducted on completion.",
	mrAddUsed: "Add Item",
	mrNoUsed: "No items yet.",
	mrItem: "Item (Service / Part)",
	mrPickItem: "Select service / part…",
	mrPhotos: "Evidence Photos",
	mrAddPhoto: "Add Photo",
	mrPhotoUploading: "Uploading…",
	mrPhotoError: "Photo upload failed",
	mrQty: "Qty",
	mrOnHand: "Stock",
	mrRemark: "Notes",
	mrRemarks: "General Notes",
	mrSearchItem: "Search item…",
	mrItemsEmpty: "Item not found.",
	mrStartFull: "Start Repair",
	mrStartFirst: "Start the repair first before it can be finished.",
	mrStart: "Start",
	mrStarted: "Repair started",
	mrInProgress: "In Progress",
	mrSave: "Save",
	mrSaved: "Saved",
	mrComplete: "Complete",
	mrCompleted: "M&R completed",
	mrSubmitReview: "Send for Review",
	mrSubmitReviewHint: "Admin Ops will check this work before the M&R is closed.",
	mrSubmittedReview: "Sent for Admin Ops review",
	mrRemove: "Remove",
	// Owner approval
	mrStatus: "Status",
	mrTotal: "Estimate Total",
	mrSubmitApproval: "Submit to Owner",
	mrSubmittedToast: "Submitted to owner",
	mrApprovalTitle: "Owner Approval",
	mrApprovalHint: "The owner decides each item. Only approved items are worked on & billed.",
	mrOwnerNote: "Owner Note",
	mrOwnerNotePlaceholder: "Reason for revision / rejection (optional)…",
	mrLineApprove: "Approve",
	mrLineReject: "Reject",
	mrApprove: "Approve All / Partial",
	mrReject: "Reject All",
	mrRequestRevision: "Request Revision",
	mrDecisionToast: "Decision saved",
	mrRevisionBanner: "The owner requested a revision. Adjust the items and submit again.",
	mrRejectedBanner: "M&R rejected by the owner.",
	mrApprovedReadonly: "Estimate approved — ready to work on.",
	mrAwaitingDecision: "Awaiting the owner's decision.",
	mrNeedItemFirst: "Add at least one item first.",
	mrExecPartsTitle: "Approved Work",
	mrPhotoCaption: "Note…",
	mrWorkPhotos: "Work Evidence Photos",
	mrNoPhotos: "No evidence photos yet.",
	mrRevisionNo: "Revision no.",
	mrExecOrdersHint: "Repairs ready to work on",
	mrExecEmpty: "No M&R ready to work on.",
	mrExecErpBanner: "This order is still under approval — managed in the ERP.",
	mrItemsCount: "jobs",
	mrFilterEmptyTodo: "All M&R have been started. 🎉",
	mrFilterEmptyStarted: "No M&R in progress yet.",
	mrReviewList: "Sent for Review",
	mrReviewEmpty: "No M&R awaiting review.",
	mrStatusPendingReview: "Pending Review",
	mrCompleteList: "Completed M&R",
	mrCompleteEmpty: "No completed M&R yet.",
	mrListMore: "See all",
	mrWithdrawReview: "Withdraw & Fix",
	mrWithdrawReviewDone: "M&R withdrawn — fix it and send it again",
	mrWithdrawReviewHint: "The order goes back to the worklist and can be worked on again.",
	mrReqRevision: "Request Revision from Admin Ops",
	mrReqRevisionHint: "Ask Admin Ops to reopen this order so it can be worked on again.",
	mrReqRevisionReason: "Revision reason (optional)",
	mrReqRevisionSend: "Send Request",
	mrReqRevisionSent: "Revision request sent to Admin Ops",
	mrReopenRequested: "Waiting for Admin Ops to reopen the order",
	// M&R redesign
	mrWorkTitle: "Repair",
	mrStatusNotStarted: "Ready",
	mrDamagesCount: "{n} EIR findings",
	mrFindingsCount: "{n} findings",
	mrApprovedBy: "approved by {name}",
	mrFromEir: "from {ref}",
	mrExFmt: "ex {cargo}",
	mrTankFromEir: "from EIR",
	mrTareMgw: "Tare / MGW",
	mrLocation: "Location",
	mrPhotoCount: "{n} photos",
	mrStartAuto: "Start time is recorded automatically.",
	mrProgressChip: "Jobs {done}/{total} photographed",
	mrStartedAt: "started {time}",
	mrTechnicianShort: "technician {name}",
	mrSubmitAutosave: "Photos & notes are saved automatically.",
	mrWorkWindow: "{start} – {end}",
	mrDurationMin: "{n} min",
	mrDuration: "Duration",
	mrWorkCount: "Jobs",
	mrItemsN: "{n} items",
	// Approval timeline
	mrFlowTitle: "Approval flow",
	mrFlowRequested: "Submitted to owner",
	mrFlowApproved: "Approved",
	mrFlowStarted: "Work started",
	mrFlowReview: "Sent for review",
	mrFlowReviewWait: "awaiting Admin Ops",
	mrFlowDone: "Completed",
	mrFlowNoTime: "time not recorded",
	// Depot Storage
	storage: "Depot Storage",
	storageDesc: "Stack & track ISO tanks by zone",
	// --- Schedule (universal calendar) ---
	scheduleTitle: "Schedule",
	scheduleHint: "Pick a date to see its work plan",
	scheduleToday: "Today",
	scheduleCount: "items",
	scheduleEmptyDay: "No work planned on this date.",
	scheduleError: "Could not load the schedule. Check your internet connection.",
	scheduleFilterAll: "All",
	scheduleOpen: "open",
	kindSurvey: "Survey",
	kindCleaning: "Cleaning",
	kindRepair: "Repair",
	kindBooking: "Booking",
	kindBookingIn: "Booking in",
	kindBookingOut: "Booking out",
	scheduleWeek: "week {n}",
	scheduleMonthOpen: "View month",
	scheduleMonthClose: "Show week",
	scheduleDone: "done",
	statusQueued: "Queued",
	statusPlanned: "Scheduled",
	statusNoBon: "No voucher yet",
	statusUnpaid: "Unpaid",
	statusArrived: "Arrived",
	statusLeft: "Left",
	scheduleNoTime: "—",
	stageDraft: "Draft",
	stageReady: "Ready",
	stageDoing: "In Progress",
	stageReview: "Awaiting Review",
	stageRevision: "Revision Requested",
	stageDone: "Completed",
	stageCancelled: "Cancelled",
	bkStatusSubmitted: "Submitted",
	bkStatusPendingPayment: "Awaiting Payment",
	bkStatusPendingConfirmation: "Awaiting Confirmation",
	bkStatusConfirmed: "Confirmed",
	bkStatusBlocked: "Blocked",
	scheduleOverdueOne: "{n} {kind} from {when} not finished",
	scheduleOverdueMixed: "{n} items from {when} not finished",
	scheduleOverdueYesterday: "yesterday",
	scheduleOverdueMore: "+{n} more on other days",
	scheduleInfoOnly: "Truck plan info",
	// --- Survey Order list ---
	surveyListTitle: "Survey Order",
	surveyListHint: "All survey schedules, including finished ones",
	surveyListSearch: "Search tank no., principal, or schedule no.…",
	surveyListEmpty: "No matching survey schedules.",
	surveyListCount: "schedules",
	surveyListFilterAll: "All",
	surveyListFrom: "From date",
	surveyListTo: "To date",
	surveyListReset: "Reset filter",
	surveyListMore: "Load more",
	surveyListFilterTitle: "Filter",
	// --- Survey Order / Container Position Survey (Tank Out) ---
	surveyPosTitle: "Field Survey Schedule",
	surveyPosDesc: "Schedule & survey tanks going out",
	surveyPosHint: "Pick a date to see its survey schedule",
	surveyPosSearch: "Search container no. / CPS…",
	surveyPosBack: "Back",
	surveyPosCount: "containers",
	// Calendar
	surveyCalToday: "Today",
	surveyCalEmptyDay: "No surveys scheduled on this date.",
	surveyCalLoading: "Loading survey schedule…",
	surveyCalError: "Could not load the survey schedule. Check your internet connection.",
	surveyCalScheduleCount: "Survey Schedules",
	// Schedule card + detail
	surveyOrderTitle: "Schedule Detail",
	surveyOrderTanksTitle: "Tank List",
	surveyOrderSurveyor: "Surveyor",
	surveyOrderPrincipal: "Principal",
	surveyOrderPickup: "Pickup",
	surveyOrderTankTotal: "tanks total",
	surveyOrderTankUnit: "tanks",
	surveyOrderEmptyTanks: "No tanks on this schedule yet.",
	surveyOrderStatusScheduled: "Ready",
	surveyOrderStatusProgress: "In Progress",
	surveyOrderStatusCompleted: "Completed",
	surveyOrderStatusCancelled: "Cancelled",
	// Tank status
	surveyPosStatusWaiting: "Waiting for Lowering",
	surveyPosStatusLowered: "Lowered",
	surveyPosStatusDone: "Survey Done",
	surveyPosStatusCancelled: "Cancelled",
	// --- Tank Position ---
	tankPosTitle: "Tank position",
	tankPosHint: "Search or scan a tank to update its position",
	tankPosSearch: "Search tank number…",
	leakHint: "Required before the tank leaves the depot.",
	leakPickTank: "Select tank",
	leakChange: "Change",
	leakPhotos: "Photos",
	leakPhotosReq: "Required, multiple allowed",
	leakFlag: "Leaking",
	leakRemarks: "Remark",
	leakRemarksHint: "General notes (optional)…",
	leakSave: "Save Leak Check",
	leakSaved: "Leak Check saved",
	leakManual: "Manual",
	listUrgentGroup: "Urgent",
	listNoDueGroup: "No target date",
	listSortPriority: "Priority",
	monitorWork: "Process",
	monitorLast: "Last",
	mrListSearch: "Search tank no., Reff Doc, order no.…",
	mrListEmpty: "No matching orders.",
	mrContinue: "Continue work",
	mrFoldedGroup: "Rejected / cancelled",
	listStatReview: "Review",
	cleaningViewRecord: "View full record",
	gateDirection: "Direction",
	listSortFar: "Latest deadline",
	listNoSurveyDate: "No survey date",
	listUrgentOnly: "Urgent only",
	eirListSearch: "Search tank no. / Reff Doc / booking / voucher…",
	listStatTodo: "Not done",
	eirTypeFilter: "EIR Type",
	eirCount: "{n} EIRs",
	eirListEmpty: "No EIRs in this list.",
	cleaningListSearch: "Search tank no. / Reff Doc / order…",
	cleaningListEmpty: "No cleaning orders.",
	cleaningContinue: "Continue cleaning",
	mrPlanDate: "Planned date",
	leakManualTitle: "Manual Leak Check",
	leakSearch: "Search tank no., Reff Doc, booking…",
	leakStatOpen: "Ready",
	leakSafe: "OK",
	leakSortOldest: "Oldest",
	leakEmpty: "No Leak Checks yet.",
	leakDetailTitle: "Leak Check",
	leakCreated: "Order created",
	leakChecked: "Checked",
	leakCheckedBy: "Checked by",
	leakPhotoCount: "{n} photos",
	leakNoRemarks: "No remarks.",
	tankPosEmpty: "No matching tanks.",
	tankPosCount: "tanks",
	tankPosFilterAll: "All",
	tankPosFilterUnlocated: "Not recorded",
	tankPosFilterOrders: "Needs checking",
	tankPosFilterHistory: "History",
	tankPosOrdersHint: "Tanks whose survey is scheduled but whose position is not recorded — or the record is older than the booking. Record the position and the tank drops off this list by itself.",
	tankPosOrdersEmpty: "All tanks waiting for survey have a position.",
	tankPosHistoryEmpty: "No position records yet.",
	tankPosUnlocated: "Position not recorded",
	tankPosUnlocatedHint: "This tank's position has never been recorded.",
	tankPosCurrent: "Current position",
	tankPosUpdate: "Update position",
	tankPosInput: "Enter position",
	tankPosSave: "Save",
	tankPosSaved: "Position saved",
	tankPosNewLabel: "New position",
	tankPosNote: "Note (optional)",
	tankPosNoteHint: "e.g. moved because a truck is using the bay",
	tankPosHistory: "Position history",
	tankPosPhotos: "Position photos",
	tankPosPhotoHint: "Photograph the stack or bay so the next person can find it easily.",
	tankPosPhotoEmpty: "No photos yet",
	tankPosPhotoCount: "photos",
	tankPosStale: "Needs rechecking",
	tankPosFresh: "Recently updated",
	tankPosBy: "by",
	// --- Tank Position: redesign ---
	tankPosDicatat: "Recorded",
	tankPosSortStale: "sort: stalest first",
	tankPosStatAll: "All",
	tankPosStatLocated: "Recorded",
	tankPosStatMissing: "Missing",
	tankPosStatRecheck: "Needs checking",
	tankPosSecRecheck: "Needs rechecking",
	tankPosSecRecheckHint: "position > {n} days old",
	tankPosSecMissing: "Not recorded",
	tankPosSecToday: "Recorded today",
	tankPosSecMore: "See {n} more",
	tankPosEnteredAt: "in",
	tankPosRecordBtn: "Record",
	tankPosBoardEmpty: "No tanks on a survey schedule",
	tankPosBoardEmptyHint: "This list only holds tanks in Tank Out booking Survey Orders. Other tanks can still be searched above.",
	// Update-position form
	tankPosNewTitle: "New position",
	tankPosTemplateFor: "Position templates · depot {depot}",
	tankPosTemplateFree: "Type freely if the position is not in the templates.",
	tankPosTemplateSaveAs: "+ Save “{label}”",
	tankPosManageTemplates: "Manage templates",
	tankPosOptional: "optional",
	tankPosPhotoOne: "1 is enough",
	tankPosAutoStamp: "Time and recorder's name are saved automatically",
	tankPosSaveWith: "Save · {label}",
	// Success
	tankPosSavedTitle: "Position saved · {label}",
	tankPosDone: "Done",
	tankPosNext: "Record next tank",
	tankPosOpenJob: "Open survey schedule →",
	// --- Manage templates ---
	tplTitle: "Position templates",
	tplShort: "Templates",
	tplSharedTitle: "Shared across one depot",
	tplSharedHint: "All {depot} staff see the same list. Items at the top appear first in the form.",
	tplAdd: "Add template",
	tplAddPlaceholder: "e.g. B5-R1 or Bay 3",
	tplAddBtn: "Add",
	tplList: "Template list",
	tplReorderHint: "arrows to reorder",
	tplUsed: "used {n}×",
	tplLastUsed: "last {t}",
	tplNeverUsed: "never used",
	tplEmpty: "No templates yet. Add the positions used most often at this depot.",
	tplSuggestTitle: "Often typed manually",
	tplSuggestNote: "not a template yet",
	tplSuggestTyped: "typed {n}× this week",
	tplSuggestMake: "+ Make template",
	tplRename: "Rename",
	tplDelete: "Delete template",
	tplDeleteAsk: "Delete template “{label}”?",
	tplDeleteBody: "The template disappears from the form for all {depot} staff. Tank positions already recorded as “{label}” do not change.",
	tplDeleteInUse: "In use",
	tplDeleteTanks: "{n} tanks",
	tplBackToForm: "Back to form",
	tplMoveUp: "Move up",
	tplMoveDown: "Move down",
	tplCancel: "Cancel",
	// --- Bulk record ---
	bulkTitle: "Record in bulk",
	bulkOpen: "Record in bulk",
	bulkIntroTitle: "One position for several tanks",
	bulkIntroHint: "Pick the tanks, then save once.",
	bulkTarget: "Target position",
	bulkTargetAll: "applies to all",
	bulkPicked: "Selected tanks",
	bulkAdd: "Add tank",
	bulkPickHint: "Search a tank number to add it.",
	bulkPrevNone: "previously not recorded",
	bulkPrev: "previously {label}",
	bulkPhotoAll: "1 photo for all",
	bulkSave: "Save {n} tanks to {label}",
	bulkSaveHint: "All are recorded with the same position.",
	bulkEmpty: "No tanks selected yet.",
	bulkPartial: "{n} tanks failed to save",
	bulkTankWord: "tanks",
	// --- Position history of one tank ---
	posHistTitle: "Position history",
	posHistMoves: "Moves",
	posHistLast: "last {n}",
	posHistMoveCount: "Moves",
	posHistTimes: "{n} times",
	posHistInDepot: "In depot",
	posHistPhotos: "{n} photos",
	posHistUpdate: "Update position",
	// Tank detail (in survey schedule)
	tankDetailTitle: "Tank Detail",
	tankDetailLocation: "Location",
	tankDetailStatus: "Tank Status",
	tankDetailHistory: "Update History",
	tankDetailEirOut: "EIR-Out",
	tankDetailWaitingMsg: "Tank has not been lowered to ground level yet.",
	tankDetailLoweredMsg: "Tank is at ground level, ready for survey.",
	tankDetailDoneMsg: "The survey for this tank is finished.",
	// Step 1 — Mark Lowered
	posLoweredAction: "Mark Lowered",
	posLoweredConfirmMsg:
		"Make sure the tank is at ground level and safe to inspect. This status can be updated by both the Surveyor and the Kalmar Operator.",
	posLoweredConfirmYes: "Yes, It's Lowered",
	posLoweredDone: "Tank marked lowered",
	posLocationLabel: "Update its position too? (optional)",
	posLocationHint: "e.g. right block near the post, stack 2",
	posLocationRequired: "This tank's position has never been recorded — fill it in now.",
	posLocationWrites: "Saved as the tank's position record, not on this schedule — so every menu picks it up right away.",
	posLoweredNote: "Lowering Note (optional)",
	posLoweredNoteHint: "e.g. lowered to the ground slot in front of the post",
	posLoweredBy: "Marked lowered by",
	posLoweredOn: "Lowering finished",
	// Step 2 — Finish Survey
	surveyFinishAction: "Do Survey",
	surveyFinishConfirmTitle: "Finish the survey?",
	surveyFinishConfirmYes: "Finish Survey",
	surveyFinishDone: "Survey finished",
	surveyFinishGate: "The tank must be marked lowered before its survey can be closed.",
	surveyFinishEirHint: "Closing the survey automatically issues a draft EIR-Out for this tank.",
	surveyPosNotes: "Survey Notes (optional)",
	surveyPosNotesHint: "Add a note (optional)…",
	surveyPosPhotos: "Photos (optional)",
	surveyPosPhotoHint: "Photos and notes are optional.",
	surveyPosSurveyedBy: "Surveyed by",
	surveyPosSurveyedOn: "Survey finished",
	// Kalmar worklist — lowering queue
	posFixTitle: "Tank Lowering",
	posFixHint: "Tank Out booking tanks still stacked up",
	posFixList: "Waiting for Lowering",
	posFixEmpty: "No tanks waiting for lowering. 🎉",
	posFixCount: "waiting",
	// --- Lowering & Survey: redesign ---
	lowTitle: "Tank lowering",
	lowHint: "Booking-out tanks still stacked up",
	lowSearch: "Search tank no. or schedule no.",
	lowStatAll: "All",
	lowStatUrgent: "Urgent",
	lowStatWaiting: "Waiting",
	lowStatLowered: "Lowered",
	lowSecUrgent: "Urgent",
	lowSecUrgentHint: "urgent or ≤ {n} days",
	lowSecWaiting: "Waiting for lowering",
	lowSecToday: "Lowered today",
	lowMark: "Mark",
	lowMarkMany: "Mark {n} at once",
	lowEmpty: "No tanks waiting for lowering",
	lowEmptyHint: "Tanks appear here when a tank-out survey schedule is created.",
	lowEmptyCta: "View survey schedule",
	lowPickup: "pickup",
	// Bulk mark
	bulkLowTitle: "Mark lowered",
	bulkLowIntro: "Several tanks at once",
	bulkLowIntroHint: "Usually lowered together from one schedule.",
	bulkLowPicked: "Selected tanks",
	bulkLowNoteAll: "applies to all",
	bulkLowSave: "Mark {n} tanks lowered",
	bulkLowHint: "Each is recorded separately in its history.",
	bulkLowDone: "{n} tanks marked lowered",
	bulkLowDoneHint: "The surveyor is notified; the survey can be done.",
	bulkLowBack: "Back to list",
	bulkLowOpenSurvey: "Open survey",
	bulkLowPartial: "{n} tanks could not be marked",
	bulkLowNeedPos: "{n} tanks have no position yet",
	bulkLowNeedPosHint: "Tanks without a position cannot be marked lowered — the surveyor has nowhere to walk to. Open them one by one and fill in the position as you go.",
	// Tank detail — two steps in one screen
	stepLowering: "Lowering",
	stepSurvey: "Survey",
	tankNotDownTitle: "Not lowered to ground level yet",
	tankNotDownBody: "Mark it lowered before the survey can be done.",
	tankUrgentTitle: "Pickup {t}, not lowered yet",
	tankUrgentBody: "Mark it lowered so the surveyor can do the survey.",
	tankReadyTitle: "At ground level, ready for survey",
	tankReadyBody: "Lowering finished {t}",
	tankMarkLowered: "Mark lowered",
	tankLoweringNote: "Lowering note",
	tankLoweringNoteHint: "e.g. lowered with the reach stacker",
	tankAutoStamp: "Time and recorder's name are saved automatically",
	tankLoweringPhotos: "Lowering photos",
	tankInteriorPhotos: "Interior photos",
	tankInteriorCaption: "Photo description…",
	tankInteriorSaving: "Saving…",
	tankDoSurvey: "Do survey",
	tankSurveyNote: "Survey note",
	tankSurveyNoteHint: "Findings during the survey",
	tankFinishSurvey: "Finish survey",
	tankFinishHint: "Closing the survey automatically issues a draft EIR-Out for this tank",
	tankSurveyDone: "Survey finished",
	tankResult: "Result",
	tankDraftEirOut: "Draft EIR-Out",
	tankUpdates: "Update history",
	tankUndo: "Undo",
	tankUndoPick: "Choose",
	// History event lines
	evScheduled: "Survey scheduled",
	evScheduledFrom: "from {ref}",
	evLowered: "Marked lowered",
	evSurveyed: "Surveyed",
	evEirOut: "Draft EIR-Out issued",
	evReopened: "Reopened",
	// --- Survey schedule list ---
	svListTitle: "Survey order",
	svListHint: "Tank-out survey schedules",
	svListSearch: "Search tank no., reff doc, company name…",
	svStatAll: "All",
	svStatScheduled: "Ready",
	svStatRunning: "In progress",
	svStatDone: "Done",
	svSecUrgent: "Urgent",
	svSecUrgentHint: "D-{n} or less",
	svChipDate: "Date",
	svChipPrincipal: "Principal",
	svChipDepot: "Depot",
	svClearAll: "Clear filters",
	svChipActive: "Active only",
	svChipSort: "Sort",
	svSortDue: "Nearest deadline",
	svSortNewest: "Newest",
	svTankCount: "{n} tanks",
	svOrderCount: "{n} orders",
	svCancelledGroup: "Cancelled",
	svCreatedBy: "Created by",
	svWorkedBy: "Worked by",
	svNotStarted: "None yet",
	svMine: "Worked by me",
	svPosNeeded: "Position update needed",
	svPosUpdate: "Update position",
	svFilterShown: "{n} of {total} tanks",
	svFilterEmpty: "No tanks for this filter.",
	svFilterShowAll: "Show all tanks",
	svHistoryTitle: "Schedule history",
	svHistoryHint: "Survey schedules that are finished or cancelled",
	svEmkl: "EMKL",
	svNoPrincipal: "Principal not filled in",
	svProgressLine: "{d} of {n} tanks surveyed",
	svContinue: "Continue survey",
	svTomorrow: "Tomorrow",
	svDaysAhead: "in {n} days",
	svDaysAgo: "{n} days overdue",
	svEmpty: "No matching survey schedules.",
	svMore: "See all",
	// Schedule detail
	svDetailTitle: "Schedule detail",
	svScheduleDate: "Survey date",
	svPickupDate: "Pick up Date",
	svSurveyor: "Surveyor",
	svStatLowered: "Lowered",
	svStatWaitingLow: "Waiting for lowering",
	svStatSurveyDone: "Survey done",
	svTankList: "Tank list",
	svReadyNote: "{n} tanks ready for survey",
	svReadyNoteHint: "The survey can be closed once all tanks are lowered.",
	svOpenTank: "Open tank · {no}",
	// Reopen (undo)
	posReopenLowering: "Send Back to Lowering",
	posReopenLoweringHint: "The tank wasn't really lowered, or its position is wrong — Kalmar redoes it.",
	posReopenSurvey: "Reopen Survey",
	posReopenSurveyHint: "The survey was closed too early — the lowering & position are kept.",
	posReopenReason: "Reason (optional)",
	posReopenReasonHint: "e.g. tank not really lowered yet",
	posReopenLoweringAsk: "Send back to lowering?",
	posReopenLoweringBody: "The tank status goes back to Waiting for lowering. Any draft EIR-Out already issued will be cancelled.",
	posReopenSend: "Send back",
	posReopenDone: "Sent back to work",
	posReopenNote: "Reopened",
	// History
	surveyPosHistoryTitle: "Position Survey History",
	surveyPosHistoryDesc: "Finished / cancelled position surveys",
	surveyPosHistoryCount: "surveys",
	// Monitor Container
	monitorTitle: "Container monitor",
	monitorSearch: "Search container number or voucher",
	monitorAll: "All",
	filterToday: "Today",
	monitorWorkedBy: "Worked by",
	monitorAllPrincipals: "All Principals",
	monitorAllDepots: "All Depots",
	monitorEmpty: "No containers for this filter.",
	monitorToday: "Today",
	// --- Container monitor (redesign) ---
	monitorAllBranch: "All branches",
	monitorTankWord: "tanks",
	monitorNoNumber: "— no no.",
	monitorDraftEir: "Draft EIR",
	monitorChipDepot: "All depots",
	monitorChipPrincipal: "Principal",
	monitorChipSort: "Sort",
	monitorSortHintActivity: "sort: latest activity",
	monitorSortHintNumber: "sort: container number",
	monitorSortHintIdle: "sort: idle longest",
	// --- Filter sheet ---
	monitorFilterTitle: "Filter",
	monitorFilterReset: "Reset",
	monitorFilterDepot: "Depot",
	monitorFilterPrincipal: "Principal · tank owner",
	monitorFilterPeriod: "Activity period",
	monitorPeriodToday: "Today",
	monitorPeriod7: "7 days",
	monitorPeriodAll: "All",
	monitorFilterSort: "Sort by",
	monitorSortActivity: "Activity",
	monitorSortNumber: "Container no.",
	monitorSortIdle: "Idle time",
	monitorCancel: "Cancel",
	monitorApply: "Apply",
	// --- Empty & error states ---
	monitorEmptyTitle: "No matching containers",
	monitorEmptyHint: "Try another number, or loosen the depot and period filters.",
	monitorEmptyReset: "Reset filter",
	monitorErrorTitle: "Could not load data",
	monitorErrorHint: "The server is not responding. Data last loaded {t}.",
	monitorErrorHintNoCache: "The server is not responding. No data is saved on this phone yet.",
	monitorRetry: "Retry",
	monitorStale: "View old data",
	monitorStaleBanner: "Old data · loaded {t}",
	// --- Container detail (track & trace) ---
	monitorDetailTitle: "Container detail",
	monitorDepotWord: "Depot",
	monitorLocationWord: "Position",
	monitorInDepot: "Time in depot",
	monitorDays: "{n} days",
	monitorProcessTitle: "Active processes",
	monitorProcessEmpty: "No work is holding this tank.",
	monitorProcessStart: "Start",
	monitorYardTitle: "Yard position",
	monitorYardEmpty: "Its position has never been recorded.",
	monitorYardRecorded: "recorded {t}",
	monitorYardOpen: "Open Tank Position",
	monitorActivityTitle: "Activity history",
	monitorActivityLast: "last {n}",
	monitorActivityAll: "View all activity",
	monitorActivityEmpty: "No activity recorded yet.",
	monitorFullHistory: "Full history",
	monitorOpenOrder: "Open {kind}",
	monitorTare: "tare",
	storageTitle: "Depot Storage",
	storagePlaceTitle: "Place ISO Tank",
	storagePlaceHint: "Enter the ISO tank number — the system suggests a zone based on status.",
	storageContainerPlaceholder: "e.g. NICU1234567",
	storageCheck: "Check Recommendation",
	storageStatus: "Status",
	storageCondition: "Condition",
	storageTargetCategory: "Target Category",
	storageCurrentPos: "Current Position",
	storageEirTitle: "Latest EIR Inspection Result",
	storageEirCargo: "Cargo",
	storageEirTank: "Tank Status",
	storageEirBy: "EIR Created By",
	storageDamages: "Damage",
	storageNoDamage: "No damage recorded.",
	storageShowPhotos: "Show photos",
	storageHidePhotos: "Hide photos",
	storageRemarks: "Remarks",
	storageNoEir: "No submitted EIR for this container yet.",
	storageRecommended: "Recommended",
	storageNoRecommend: "No zone matches this status.",
	storageNoDepot: "Container is not assigned to a depot — set its depot first (Container master) before arranging zones.",
	storageSelectZone: "Select placement zone",
	storageManualPick: "Pick zone manually / other",
	storageRow: "Row",
	storageTier: "Tier",
	storageBay: "Bay",
	storageOptional: "optional",
	storagePlace: "Place",
	storagePlaced: "ISO tank placed",
	storageOccupancy: "Zone Occupancy",
	storageFull: "Full",
	storageSlotsFree: "slots free",
	storageNoZones: "No zones for this depot yet.",
	storageZoneTanks: "ISO tanks in zone",
	storageNoTanks: "No ISO tanks in this zone yet.",
	storageSop: "Stacking SOP Guide",
	storageBranch: "Branch",
	storageLoadMore: "Load more",
	storageSearchTank: "Search container number…",
	storageShowing: "shown",
	storageOf: "of",
	// --- moved in for i18n
	close: "Close",
	remove: "Remove",
	confirmTitle: "Confirm",
	confirmYes: "Yes",
	selectEmpty: "No results.",
	liftUrgent: "URGENT",
	liftOverdue: "{d} d overdue",
	liftToday: "D-day",
	liftDaysLeft: "D-{d}",
	sinceJustNow: "Just now",
	sinceMinutes: "{n} min ago",
	sinceHours: "{n} h ago",
	sinceDays: "{n} days ago",
	scheduleDow: "Mo,Tu,We,Th,Fr,Sa,Su",
	dueToday: "today",
	dueTomorrow: "tomorrow",
	tankPosAt: "position {p}",
	tankSurveyorBy: "surveyor {s}",
	depotOf: "depot {d}",
	eirInIntoDepot: "entered depot {d}",
	gateOutReadyOf: "of",
	allBranches: "All Branches",
	sendPhotoMissing: "Photo not found in local storage.",
	sendOffline: "No connection to the server.",
	sendSessionExpired: "Session expired, log in again.",
	sendServerDown: "Server is not responding ({status}).",
	langTitle: "Language / Bahasa",
}

export const statusLabels = {
	available: "Ready to Leave",
	draft: "Draft",
	pending: "Ready",
	in_progress: "In Progress",
	gate_out: "Left",
}

export const repairStatusLabels = {
	Draft: "Draft",
	"Pending Approval": "Awaiting Approval",
	Approved: "Approved",
	Rejected: "Rejected",
	"Revision Requested": "Revision Requested",
	Pending: "Ready",
	"In Progress": "In Progress",
	"Pending Review": "Awaiting Review",
	Completed: "Completed",
	Cancelled: "Cancelled",
}

export const directionLabels = {
	"Tank In": "Tank In",
	"Tank Out": "Tank Out",
}

export const gateDirections = {
	"Tank In": { label: "GATE IN", desc: "Container entering the depot" },
	"Tank Out": { label: "GATE OUT", desc: "Container leaving the depot" },
}
